import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import PoweredBySefaria from './poweredbysefariablue.png';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="flex items-center justify-center gap-4 p-4 bg-gray-100 dark:bg-gray-800">
          <Image src={PoweredBySefaria} height={80} alt="Powered by Sefaria"/>
        </footer>
      </body>
    </html>
  );
}
